site:
  title: Redpanda Docs
  start_page: ROOT:home:index.adoc
  url: http://localhost:5002
urls:
  html_extension_style: indexify
  latest_version_segment: 'current'
output:
  clean: true
content:
  sources:
  - url: https://github.com/redpanda-data/documentation-private
    branches: [main, v/*, api, shared, site-search]
ui:
  bundle:
    url: https://github.com/redpanda-data/docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
  extensions:
  - '@asciidoctor/tabs'
  - '@redpanda-data/docs-extensions-and-macros/macros/glossary'
  - '@redpanda-data/docs-extensions-and-macros/macros/config-ref'
  - '@redpanda-data/docs-extensions-and-macros/macros/helm-ref'
antora:
  extensions:
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/unlisted-pages'
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/add-global-attributes'
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/aggregate-terms'
