[build.environment]
NODE_VERSION = "16"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = "home/index.html"

  [plugins.inputs.settings]
    preset = "desktop"

# For future use. Allows us to host docs under the `/api/` path that other services such as Redpanda Cloud can consume.
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# NOTE the following redirects get appended to the redirects defined in the _redirects file

[[redirects]]
from = "/docs/home/*"
to = "/home"
status = 301

[[redirects]]
from = "/docs/23.1/home"
to = "/home"
status = 301

[[redirects]]
from = "/docs/22.3/home"
to = "/home"
status = 301

[[redirects]]
from = "/docs/22.2/home"
to = "/home"
status = 301

[[redirects]]
from = "/docs/22.1/home"
to = "/home"
status = 301

[[redirects]]
from = "/docs/21.11/home"
to = "/home"
status = 301

[[redirects]]
from = "/docs/23.1/*"
to = "/23.1/:splat"
status = 301

[[redirects]]
from = "/docs/22.3/*"
to = "/22.3/:splat"
status = 301

[[redirects]]
from = "/docs/22.2/*"
to = "/22.2/:splat"
status = 301

[[redirects]]
from = "/docs/22.1/*"
to = "/22.1/:splat"
status = 301

[[redirects]]
from = "/docs/21.11/*"
to = "/21.11/:splat"
status = 301

[[redirects]]
from = "/docs/api/*"
to = "/api/:splat"
status = 301

[[redirects]]
from = "/docs/cloud/*"
to = "/current/deploy/deployment-option/cloud/:splat"
status = 301

[[redirects]]
from = "/docs/platform/reference/*"
to = "/current/reference/:splat"
status = 301

[[redirects]]
from = "/docs/*"
to = "/current/:splat"
status = 301
